version: '3.8'

services:
  coffeechat:
    build: .
    container_name: private-coffeechat
    ports:
      - "33333:33333"
    volumes:
      # 데이터베이스 영속성
      - ./user.db:/app/user.db
      # Google OAuth 토큰 영속성
      - ./token.json:/app/token.json
      - ./client_secret.json:/app/client_secret.json
      # 환경변수 파일
      - ./.env.prod:/app/.env.prod
    environment:
      - FLASK_ENV=production
      - FLASK_PORT=33333
    restart: unless-stopped
    networks:
      - coffeechat-network

networks:
  coffeechat-network:
    driver: bridge
